### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by torstenwerner** [OpenDataSpace/chemistry-shell#1]
Hi,

I am getting an error during build
`[ERROR] Failed to execute goal on project chemistry-shell: Could not resolve dependencies for project org.apache.chemistry:chemistry-shell:jar:0.6.207: Failure to find org.apache.chemistry.opencmis:chemistry-opencmis-client-impl:jar:1.0.0-187 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]`
I found version 0.13.0 on maven.org. Am I doing something wrong?

Best Regards,
Torsten

**Comment by soneyworld** [comment]
Hi,

thanks a lot for your feedback. You are right. Please downgrade the pom.xml dependency to 0.13.0 on your own clone. It seems to be an issue in our automatic build system. It should work fine with 0.13.0

I am very sorry for this inconvenience. I'll check if we can fix this issue and will inform you about the status.

Best regards,
Till

**Comment by soneyworld** [comment]
Hi again,

the easiest way is to downgrade the dependency to version 0.13.0
If you are interested in our version: clone https://github.com/OpenDataSpace/chemistry-opencmis and check out the requested version (git tag) and build it on your own.

Best regards,
Till
